var dutch = {
    settings: {
        translatable    : 1,
        max_names_count : 3,
        title           : "Генератор подбора нидерландских, голландских, бельгийских имен и фамилий"
    },

    name_m: [
        "Adam | Адам",
        "Adriaan | Адриан",
        "Albert | Алберт",
        "Alexander | Александер",
        "Alfons | Алфонс",
        "Alfred | Алфред",
        "Andreas | Андреас",
        "Antoon | Антон",
        "Arthur | Артур",
        "Bart | Барт",
        "Benjamin | Беньямин",
        "Bernard | Бернард",
        "Bert | Берт",
        "Bram | Брам",
        "Brecht | Брехт",
        "Bruno | Бруно",
        "Camiel | Камил",
        "Casper | Каспер",
        "Christiaan | Кристиан",
        "Christian | Кристиан",
        "Cornelis | Корнелис",
        "Damian | Дамиан",
        "Daniël | Даниэл",
        "David | Давид",
        "Dennis | Деннис",
        "Dirk | Дирк",
        "Dries | Дрис",
        "Elias | Элиас",
        "Emiel | Эмил",
        "Emmanuel | Эммануэл",
        "Erik | Эрик",
        "Fedde | Федде",
        "Ferdinand | Фердинанд",
        "Filip | Филип",
        "Floris | Флорис",
        "Franciscus | Франсискус",
        "Frank | Франк",
        "Frans | Франс",
        "Frederik | Фредерик",
        "Gabriël | Габриэл",
        "Geert | Герт",
        "Gerrit | Геррит",
        "Gert | Герт",
        "Gijs | Гейс",
        "Guido | Гвидо",
        "Gustaaf | Густаф",
        "Guus | Гус",
        "Hans | Ханс",
        "Hendrik | Хендрик",
        "Herman | Херман",
        "Hidde | Хидде",
        "Hugo | Хуго",
        "Ivo | Иво",
        "Jacobus | Якобус",
        "Jan | Ян",
        "Jasper | Яспер",
        "Jelle | Йелле",
        "Jeroen | Йерун",
        "Joachim | Йоахим",
        "Joannes | Йоаннес",
        "Johan | Йохан",
        "Johannes | Йоханнес",
        "Jonas | Йонас",
        "Jonathan | Йонатан",
        "Joost | Йост",
        "Joris | Йорис",
        "Josephus | Йозефус",
        "Jozef | Йозеф",
        "Juliaan | Юлиан",
        "Julius | Юлиус",
        "Jurgen | Юрген",
        "Karel | Карел",
        "Klaas | Клас",
        "Koenraad | Кунрад",
        "Kurt | Курт",
        "Lander | Ландер",
        "Laurens | Лауренс",
        "Lennert | Леннерт",
        "Leo | Лео",
        "Leopold | Леополд",
        "Lieven | Ливен",
        "Lodewijk | Лодевейк",
        "Lucas | Лукас",
        "Ludo | Лудо",
        "Maarten | Мартен",
        "Mark | Марк",
        "Mathijs | Матейс",
        "Matthias | Маттиас",
        "Maurits | Мауритс",
        "Michiel | Михил",
        "Nathan | Натан",
        "Norbert | Норберт",
        "Oscar | Оскар",
        "Pepijn | Пепейн",
        "Peter | Петер",
        "Petrus | Петрус",
        "Pieter | Питер",
        "Pieter-Jan | Питер-Ян",
        "Quinten | Квинтен",
        "Raphaël | Рафаэл",
        "René | Рене",
        "Robert | Роберт",
        "Roel | Рул",
        "Roeland | Руланд",
        "Ruben | Рубен",
        "Rudolf | Рудолф",
        "Samuël | Самуэл",
        "Sebastiaan | Себастьян",
        "Siebe | Сибе",
        "Simon | Симон",
        "Stefan | Стефан",
        "Stijn | Стейн",
        "Theodoor | Теодор",
        "Theophiel | Теофил",
        "Thijmen | Теймен",
        "Thijs | Тейс",
        "Thomas | Томас",
        "Timo | Тимо",
        "Tobias | Тобиас",
        "Valentijn | Валентейн",
        "Victor | Виктор",
        "Vincent | Винсент",
        "Willem | Виллем",
        "Wouter | Ваутер"
    ],
    name_f: [
        "Adriana | Адриана",
        "Agnes | Агнес",
        "Andrea | Андреа",
        "Anita | Анита",
        "Anja | Аня",
        "Anke | Анке",
        "Anna | Анна",
        "Anneleen | Аннелен",
        "Annelies | Аннелис",
        "Annemie | Аннеми",
        "Augusta | Августа",
        "Barbara | Барбара",
        "Bertha | Берта",
        "Brigitta | Бригитта",
        "Carla | Карла",
        "Cecilia | Сесилия",
        "Christa | Криста",
        "Christel | Кристел",
        "Christiana | Кристиана",
        "Christina | Кристина",
        "Clara | Клара",
        "Cornelia | Корнелия",
        "Diana | Диана",
        "Dina | Дина",
        "Edith | Эдит",
        "Elisabeth | Элизабет",
        "Elke | Элке",
        "Emilie | Эмили",
        "Emma | Эмма",
        "Erika | Эрика",
        "Erna | Эрна",
        "Esmée | Эсме",
        "Esther | Эстер",
        "Eva | Эва",
        "Evelien | Эвелин",
        "Fanny | Фанни",
        "Femke | Фемке",
        "Fenna | Фенна",
        "Fien | Фин",
        "Francisca | Франсиска",
        "Frieda | Фрида",
        "Gerarda | Герарда",
        "Gerda | Герда",
        "Godelieve | Годеливе",
        "Greta | Грета",
        "Hanne | Ханне",
        "Heidi | Хейди",
        "Helena | Хелена",
        "Henriette | Хенриэтте",
        "Hilde | Хилде",
        "Ida | Ида",
        "Ine | Ине",
        "Irena | Ирена",
        "Irma | Ирма",
        "Janne | Янне",
        "Joanna | Йоанна",
        "Johanna | Йоханна",
        "Joke | Йоке",
        "Julia | Юлия",
        "Juliana | Юлиана",
        "Karen | Карен",
        "Karolien | Каролин",
        "Katrien | Катрин",
        "Krista | Криста",
        "Laura | Лаура",
        "Leen | Лен",
        "Leona | Леона",
        "Lien | Лин",
        "Linda | Линда",
        "Lotte | Лотте",
        "Louisa | Луиза",
        "Magdalena | Магдалена",
        "Marcella | Марселла",
        "Margaretha | Маргарета",
        "Maria | Мария",
        "Marina | Марина",
        "Marleen | Марлен",
        "Martha | Марта",
        "Martina | Мартина",
        "Mathilda | Матилда",
        "Melanie | Мелани",
        "Melissa | Мелисса",
        "Merel | Мерел",
        "Mirthe | Мирте",
        "Monique | Моник",
        "Myriam | Мириам",
        "Nathalie | Натали",
        "Nele | Неле",
        "Nelly | Нелли",
        "Nienke | Нинке",
        "Nina | Нина",
        "Nora | Нора",
        "Patricia | Патрисия",
        "Paula | Паула",
        "Petra | Петра",
        "Philomena | Филомена",
        "Rebecca | Ребекка",
        "Regina | Регина",
        "Renske | Ренске",
        "Renée | Рене",
        "Rosa | Роза",
        "Rosalia | Розалия",
        "Ruth | Рут",
        "Sandra | Сандра",
        "Sarah | Сара",
        "Saskia | Саския",
        "Silke | Силке",
        "Simona | Симона",
        "Sofie | Софи",
        "Sonja | Соня",
        "Stefanie | Стефани",
        "Sterre | Стерре",
        "Suzanna | Сузанна",
        "Sylvia | Силвия",
        "Tania | Таня",
        "Tessa | Тесса",
        "Tine | Тине",
        "Veerle | Верле",
        "Vera | Вера",
    ],
    cognomen: [
        "'t Hart | 'т Харт",
        "Aalderink | Алдеринк",
        "Abbink | Аббинк",
        "Adam | Адам",
        "Aerts | Артс",
        "Baert | Барт",
        "Bakker | Баккер",
        "Bauwens | Баувенс",
        "Beckers | Беккерс",
        "Boender | Бундер",
        "Boer | Бур",
        "Bogaert | Богарт",
        "Bogaerts | Богартс",
        "Bos | Бос",
        "Bosman | Босман",
        "Bosmans | Босманс",
        "Brabander | Брабандер",
        "Brander | Брандер",
        "Brouwer | Брауэр",
        "Christiaens | Кристианс",
        "Claes | Клас",
        "Claessens | Классенс",
        "Cools | Колс",
        "Coppens | Коппенс",
        "Dekker | Деккер",
        "Desmet | Десмет",
        "Devos | Девос",
        "Dijkstra | Дейкстра",
        "Driessen | Дриссен",
        "Eilander | Эйландер",
        "Geerts | Гертс",
        "Gerritsen | Герритсен",
        "Goossens | Госсенс",
        "Groen | Грун",
        "Hendrickx | Хендриккс",
        "Hendriks | Хендрикс",
        "Hermans | Херманс",
        "Jacobs | Якобс",
        "Jansen | Янсен",
        "Janssen | Янссен",
        "Janssens | Янссенс",
        "Jonker | Йонкер",
        "Kok | Кок",
        "Koning | Конинг",
        "Koster | Костер",
        "Kuiper | Кёйпер",
        "Kuipers | Кёйперс  ",
        "Lambrechts | Ламбрехтс",
        "Lemmens | Лемменс",
        "Lenaerts | Ленартс",
        "Maas | Мас",
        "Maes | Мас",
        "Martens | Мартенс",
        "Meijer | Мейер",
        "Mertens | Мертенс",
        "Meyer | Мейер",
        "Michiels | Михилс",
        "Moens | Мунс",
        "Molenaar | Моленар",
        "Mulder | Мулдер",
        "Pauwels | Пауэлс",
        "Peeters | Петерс",
        "Peters | Петерс",
        "Pieters | Питерс",
        "Sanders | Сандерс",
        "Sasbrink | Сасбринк",
        "Segers | Сегерс",
        "Simons | Симонс",
        "Smeets | Сметс",
        "Smet | Смет",
        "Smets | Сметс",
        "Smit | Смит",
        "Smits | Смитс",
        "Thys | Тис",
        "Timmermans | Тиммерманс",
        "Vedder | Веддер",
        "Veenstra | Венстра",
        "Verbeek | Вербек",
        "Verbeke | Вербеке",
        "Verhoeven | Верхувен",
        "Verlinden | Верлинден",
        "Vermeiren | Вермейрен",
        "Verstraeten | Верстратен",
        "Vink | Винк",
        "Visser | Виссер",
        "Vos | Вос",
        "Wauters | Ваутерс",
        "Willems | Виллемс",
        "Willemsen | Виллемсен",
        "Wouters | Ваутерс",
        "de Backer | де Баккер",
        "de Boer | де Бур",
        "de Coninck | де Конинк",
        "de Croon | де Крон",
        "de Graaf | де Граф",
        "de Groot | де Грот",
        "de Haan | де Хан",
        "de Jong | де Йонг",
        "de Jonge | де Йонге",
        "de Koning | де Конинг",
        "de Kooker | де Кокер",
        "de Lange | де Ланге",
        "de Meyer | де Мейер",
        "de Ridder | де Риддер",
        "de Ruiter | де Рёйтер",
        "de Smedt | де Смедт",
        "de Smet | де Смет",
        "de Valk | де Валк",
        "de Veen | де Вен",
        "de Veer | де Вер",
        "de Vos | де Вос",
        "de Vries | де Врис  ",
        "de Wilde | де Вилде",
        "de Winter | де Винтер",
        "de Wit | де Вит",
        "de clercq | де Клерк",
        "ten Wolde | тен Волде",
        "ter Linde | тер Линде",
        "van Beek | ван Бек  ",
        "van Dam | ван Дам",
        "van Dijk | ван Дейк",
        "van Dongen | ван Донген",
        "van Doorn | ван Дорн  ",
        "van Loon | ван Лон",
        "van Veen | ван Вен",
        "van Wijk | ван Вейк",
        "van de Berg | ван де Берг",
        "van de Brink | ван де Бринк",
        "van de Veen | ван де Вен",
        "van de Velde | ван де Велде",
        "van de Velden | ван де Велден",
        "van den Berg | ван ден Берг",
        "van den Brink | ван ден Бринк",
        "van den Broek | ван ден Брук",
        "van den Pol | ван ден Пол",
        "van den Velde | ван ден Велде",
        "van der Berg | ван дер Берг  ",
        "van der Heijden | ван дер Хейден",
        "van der Horst | ван дер Хорст",
        "van der Laan | ван дер Лан",
        "van der Linden | ван дер Линден",
        "van der Meer | ван дер Мер",
        "van der Pol | ван дер Пол",
        "van der Velde | ван дер Велде",
        "van der Ven | ван дер Вен",
        "van der Wal | ван дер Вал",
        "van der Wolf | ван дер Волф",
        "van der Woude | ван дер Вауде",
        "van der Zee | ван дер Зе",
    ],
    cognomen_f : [
        "Aalderink | Алдеринк",
        "Abbink | Аббинк",
        "Adam | Адам",
        "Aerts | Артс",
        "Baert | Барт",
        "Bakker | Баккер",
        "Bauwens | Баувенс",
        "Beckers | Беккерс",
        "Boender | Бундер",
        "Boer | Бур",
        "Bogaert | Богарт",
        "Bogaerts | Богартс",
        "Bos | Бос",
        "Bosman | Босман",
        "Bosmans | Босманс",
        "Brabander | Брабандер",
        "Brander | Брандер",
        "Brouwer | Брауэр",
        "Christiaens | Кристианс",
        "Claes | Клас",
        "Claessens | Классенс",
        "Cools | Колс",
        "Coppens | Коппенс",
        "De Backer | Де Баккер",
        "De Boer | Де Бур  ",
        "De Clercq | Де Клерк",
        "De Coninck | Де Конинк",
        "De Croon | Де Крон",
        "De Graaf | Де Граф",
        "De Groot | Де Грот",
        "De Haan | Де Хан",
        "De Jong | Де Йонг",
        "De Jonge | Де Йонге",
        "De Koning | Де Конинг",
        "De Kooker | Де Кокер",
        "De Lange | Де Ланге",
        "De Meyer | Де Мейер",
        "De Ridder | Де Риддер",
        "De Ruiter | Де Рёйтер",
        "De Smedt | Де Смедт",
        "De Smet | Де Смет",
        "De Valk | Де Валк",
        "De Veen | Де Вен",
        "De Veer | Де Вер",
        "De Vos | Де Вос",
        "De Vries | Де Врис",
        "De Wilde | Де Вилде",
        "De Winter | Де Винтер",
        "De Wit | Де Вит",
        "Declercq | Деклерк",
        "Dekker | Деккер",
        "Desmet | Десмет",
        "Devos | Девос",
        "Dijkstra | Дейкстра",
        "Driessen | Дриссен",
        "Eilander | Эйландер",
        "Geerts | Гертс",
        "Gerritsen | Герритсен",
        "Goossens | Госсенс",
        "Groen | Грун",
        "Hendrickx | Хендриккс",
        "Hendriks | Хендрикс",
        "Hermans | Херманс",
        "Jacobs | Якобс",
        "Jansen | Янсен",
        "Janssen | Янссен",
        "Janssens | Янссенс",
        "Jonker | Йонкер",
        "Kok | Кок",
        "Koning | Конинг",
        "Koster | Костер",
        "Kuiper | Кёйпер",
        "Kuipers | Кёйперс",
        "Lambrechts | Ламбрехтс",
        "Lemmens | Лемменс",
        "Lenaerts | Ленартс",
        "Maas | Мас",
        "Maes | Мас",
        "Martens | Мартенс",
        "Meijer | Мейер",
        "Mertens | Мертекс",
        "Meyer | Мейер",
        "Michiels | Михилс",
        "Moens | Мунс",
        "Molenaar | Моленар",
        "Mulder | Мулдер",
        "Pauwels | Пауэлс",
        "Peeters | Петерс",
        "Peters | Петерс",
        "Pieters | Питерс",
        "Sanders | Сандерс",
        "Sasbrink | Сасбринк",
        "Segers | Сегерс",
        "Simons | Симонс",
        "Smeets | Сметс",
        "Smet | Смет",
        "Smets | Сметс",
        "Smit | Смит",
        "Smits | Смитс",
        "Ten Wolde | Тен Волде",
        "Ter Linde | Тер Линде",
        "Thys | Тис",
        "Timmermans | Тиммерманс",
        "Van Beek | Ван Бек",
        "Van Dam | Ван Дам",
        "Van De Berg | Ван Де Берг",
        "Van De Brink | Ван Де Бринк",
        "Van De Veen | Ван Де Вен",
        "Van De Velde | Ван Де Велде",
        "Van De Velden | Ван Де Велден",
        "Van Den Berg | Ван Ден Берг",
        "Van Den Brink | Ван Ден Бринк",
        "Van Den Broek | Ван Ден Брук",
        "Van Den Pol | Ван Ден Пол",
        "Van Den Velde | Ван Ден Велде",
        "Van Der Berg | Ван Дер Берг  ",
        "Van Der Heijden | Ван Дер Хейден",
        "Van Der Horst | Ван Дер Хорст",
        "Van Der Laan | Ван Дер Лан",
        "Van Der Linden | Ван Дер Линден",
        "Van Der Meer | Ван Дер Мер",
        "Van Der Pol | Ван Дер Пол",
        "Van Der Velde | Ван Дер Велде",
        "Van Der Ven | Ван Дер Вен",
        "Van Der Wal | Ван Дер Вал",
        "Van Der Wolf | Ван Дер Волф",
        "Van Der Woude | Ван Дер Вауде",
        "Van Der Zee | Ван Дер Зе",
        "Van Dijk | Ван Дейк",
        "Van Dongen | Ван Донген",
        "Van Doorn | Ван Дорн",
        "Van Loon | Ван Лон",
        "Van Veen | Ван Вен",
        "Van Wijk | Ван Вейк",
        "Vedder | Веддер",
        "Veenstra | Венстра",
        "Verbeek | Вербек",
        "Verbeke | Вербеке",
        "Verhoeven | Верхувен",
        "Verlinden | Верлинден",
        "Vermeiren | Вермейрен",
        "Verstraeten | Верстратен",
        "Vink | Винк",
        "Visser | Виссер",
        "Vos | Вос",
        "Wauters | Ваутерс",
        "Willems | Виллемс",
        "Willemsen | Виллемсен",
        "Wouters | Ваутерс",
    ],


    getRandomName: function (gender) {
        let result = '';
        let rnd = 0;
        let original = '';
        let transtalted = '';

        var name_source;

        // установим namearray сообразно гендеру
        if (gender == "male") {
            name_source = this.name_m;
        }
        if (gender == "female") {
            name_source = this.name_f;
        }

        // генерируем имя
        result = engine.getRndNameParts(name_source);

        original += result[0] + ' ';
        transtalted += result[1] + ' ';

        // генерируем фамилию
        result = engine.getRndNameParts(this.cognomen);

        original += result[0];
        transtalted += result[1];

        return {
            'original': original,
            'translated': transtalted
        };
    },

    printName: function (string) {
        return out = string.translated + ' ( ' + string.original + ' ) '
    }
};



